### ISSUE TITLE
misleading message

### ISSUE THREAD

**Issue by odinuv** [keboola/ex-ftp#10]
https://github.com/keboola/ex-ftp/blob/0a2d22f9b92814261ca7f1ca91ee740c70ea5985/src/FtpExtractor.php#L88

**Comment by eddycek** [comment]
@odinuv už je tam lepší msg https://github.com/keboola/ex-ftp/blob/master/src/FtpExtractor.php#L120

**Comment by eddycek** [comment]
uzavřel bych to
