### ISSUE TITLE
ftp_rawlist(): php_connect_nonb() failed: Operation now in progress (115)

### ISSUE THREAD

**Issue by MiroCillik** [keboola/ex-ftp#11]
![Alt text](https://monosnap.com/image/y9tH3xUQZw2ZTjCUxUYmMqiUzfEHhe.png)

Should have better error message, if it is a known issue.

Also I've read something about setting `FTP_USEPASVADDRESS ` to false might help solve this error. 
https://serverfault.com/questions/797928/php-ftp-passive-ftp-server-behind-nat

Or it might be problem with port forwarding / firewall.
https://stackoverflow.com/questions/15688331/php-connect-nonb-failed-operation-now-in-progress-115-happens-intermitten

**Comment by pivnicek** [comment]
Sorry @eddycek , happened again today
https://keboola.slack.com/archives/C09U3R1J4/p1569992081009500
https://keboola.zendesk.com/agent/tickets/11706

**Comment by eddycek** [comment]
Koukal jsem na to, vyřeším to v https://github.com/keboola/ex-ftp/pull/27, až projde PR do `thephpleague/flysystem`.

**Comment by kacurez** [comment]
stalo sa to znovu - https://keboola.zendesk.com/agent/tickets/12025
Ake je teda odporucanie pre klienta ktoremu to pada na takejto chybe? Aby si na svojom ftp servri povolil vsetky porty?

**Comment by eddycek** [comment]
@kacurez pravděpodobně jde o blokaci ze strany Firewallu nebo nějakého portu. Nejlepší je povolit komunikaci všech portu nebo vypnout Firewall. Bohužel víc informací aktuálně nedokážu dodat.

**Comment by michaljurecko** [comment]
Bolo to osetrene (aby sa vypisala zrozumitelna sprava) iba pre `ExceptionConverter::handleDownloadException()`, ... podla logov to moze nastat aj v  `handlePrepareToDownloadException`, a teda osetrim aj ostatne pripady a pridam test.
