### ISSUE TITLE
Component out of memory

### ISSUE THREAD

**Issue by ujovlado** [keboola/ex-ftp#13]
https://keboola.slack.com/archives/C09U3R1J4/p1553852542006000

neskumal som cim to je, pre zatial som to zdvihol na 1024m a uvidime

**Comment by yustme** [comment]
To je dost zvláštní, protože stahuje 1 soubor a dává tam přímou cestu. Už je u tý komponenty víc issue. Pověnuju se tomu co dodělám orchestrace.

**Comment by odinuv** [comment]
objevilo se to zase, jiny projekt, jina konfigurace https://connection.eu-central-1.keboola.com/admin/projects/399/extractors/keboola.ex-ftp/37295744/rows/40542495

**Comment by odinuv** [comment]
uz jsem to musel zvysit na 2G

**Comment by natocTo** [comment]
Včera zase problém při stahování jednoho souboru (cca 2gb) - jen pro test jsem to zvedl na 3G zda to mohlo být pamětí a pak to prošlo.. https://app.slack.com/client/T5BLE3NEL/CGCKT849E/thread/CGCKT849E-1581608659.004600

**Comment by odinuv** [comment]
@ondrajodas

**Comment by zajca** [comment]
Založil sem sem bug report https://keboola.atlassian.net/browse/COM-1201 takže to tady zavírám.
