### ISSUE TITLE
Lovely error

### ISSUE THREAD

**Issue by odinuv** [keboola/ex-ftp#17]
CRITICAL: ErrorException:ftp_fget(): php_connect_nonb() failed: Operation now in progress (115) 

https://keboola.slack.com/archives/C09U3R1J4/p1557794282123000

**Comment by odinuv** [comment]
{\"errFile\":\"\/code\/vendor\/league\/flysystem\/src\/Adapter\/Ftp.php\",\"errLine\":458,\"errCode\":0,\"errTrace\":\"#0 [internal function]: Keboola\\\\Component\\\\BaseComponent::Keboola\\\\Component\\\\{closure}(2, 'ftp_fget(): php...', '\/code\/vendor\/le...', 458, Array)\\n#1 \/code\/vendor\/league\/flysystem\/src\/Adapter\/Ftp.php(458): ftp_fget(Resource id #226618, Resource id #417799, 'Palubaky\/7854\/O...', 2)\\n#2 \/code\/vendor\/league\/flysystem\/src\/Adapter\/Ftp.php(441): League\\\\Flysystem\\\\Adapter\\\\Ftp->readStream('Palubaky\/7854\/O...')\\n#3 \/code\/vendor\/league\/flysystem\/src\/Filesystem.php(181): League\\\\Flysystem\\\\Adapter\\\\Ftp->read('Palubaky\/7854\/O...')\\n#4 \/code\/src\/FtpExtractor.php(152): League\\\\Flysystem\\\\Filesystem->read('Palubaky\/7854\/O...')\\n#5 \/code\/src\/FtpExtractor.php(54): Keboola\\\\FtpExtractor\\\\FtpExtractor->download(Object(Keboola\\\\FtpExtractor\\\\FileStateRegistry))\\n#6 \/code\/src\/FtpExtractorComponent.php(26): Keboola\\\\FtpExtractor\\\\FtpExtractor->copyFiles('Palubaky\/*\/Occu...', '\/data\/out\/files...', Object(Keboola\\\\FtpExtractor\\\\FileStateRegistry))\\n#7 \/code\/src\/run.php(14): Keboola\\\\FtpExtractor\\\\FtpExtractorComponent->run()\\n#8 {main}\",\"errPrevious\":[hidden]}

**Comment by eddycek** [comment]
Imho tady jde nejspíš o nějakou blokaci ze strany firewallu, ale úplně nevím jak to nasimulovat abych si to otestoval.

**Comment by eddycek** [comment]
viz https://stackoverflow.com/questions/15688331/php-connect-nonb-failed-operation-now-in-progress-115-happens-intermitten

**Comment by eddycek** [comment]
Jo a asi je to duplicitní issue k #11

**Comment by yustme** [comment]
Nahodit FTP v dockeru, kde zablokuješ všechny porty, které nejsou 21? 

A nebo jenom ošetřit to místo, kde se vyhazuje ta chyba a napsat tam něco jako "Connection was terminated. Possible issues .. . "

**Comment by eddycek** [comment]
@yustme To mě taky napadlo, ale v tomhle případě je problém až u čtení souboru, dochází k tomu přesně zde https://github.com/keboola/ex-ftp/blob/master/src/FtpExtractor.php#L184

**Comment by yustme** [comment]
Tak to možná zachytávat už úplně nahoře ?

**Comment by yustme** [comment]
Nebo udělat PR do původní knihovny ? a vyhazovat nějakou rozumnou vyjímku při čtění ?

**Comment by eddycek** [comment]
Dost se toho vyřeší když schválí PR co jsem už poslal do `flysystem-sftp`. Ostatní dotáhnu v PR https://github.com/keboola/ex-ftp/pull/23 kde už jsem zapracoval i tento problém.
