### ISSUE TITLE
ErrorException:Connection closed prematurely 

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/ex-ftp#19]
```

#0 [internal function]: Keboola\Component\BaseComponent::Keboola\Component\{closure}(1024, 'Connection clos...', '/code/vendor/ph...', 3945, Array)
#1 /code/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3945): user_error('Connection clos...')
#2 /code/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4162): phpseclib\et\SSH2->_send_binary_packet('\x01\x00\x00\x00\v\x00\x00\x00\x00\x00\x00\x00\x00')
#3 /code/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3112): phpseclib\et\SSH2->_disconnect(11)
#4 /code/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3207): phpseclib\et\SFTP->_disconnect(11)
#5 /code/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3223): phpseclib\et\SSH2->disconnect()
#6 /code/vendor/league/flysystem-sftp/src/SftpAdapter.php(360): phpseclib\et\SSH2->__destruct()
#7 /code/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(609): League\Flysystem\Sftp\SftpAdapter->disconnect()
#8 /code/src/FtpExtractorComponent.php(26): League\Flysystem\Adapter\AbstractFtpAdapter->__destruct()
#9 /code/src/run.php(14): Keboola\FtpExtractor\FtpExtractorComponent->run()
#10 {main}
```

**Comment by kacurez** [comment]
again https://keboola.slack.com/archives/C09U3R1J4/p1565020593000800

**Comment by kacurez** [comment]
na jednom projekte to teraz pada kazdu hodinu kedze maju takto nastavenu orchestraciu. Asi by bolo dobre skusit dorobit retry alebo vyhodnotit ako user error

**Comment by kacurez** [comment]
zacalo sa to objavovat znova na projekte ineho klienta
https://keboola.slack.com/archives/C09U3R1J4/p1565166254006400

**Comment by pivnicek** [comment]
zase: https://keboola.zendesk.com/agent/tickets/12550

**Comment by pivnicek** [comment]
imho we should wrap the whole job (ie this: https://github.com/keboola/ex-ftp/blob/master/src/FtpExtractorComponent.php#L24 to L34 in a retry.  currently it looks like it is only retrying creating the connection.

**Comment by pivnicek** [comment]
Related is https://github.com/keboola/retry/issues/17 that the Simple Policy does not retry ErrorException 🤦‍♂

**Comment by ujovlado** [comment]
https://keboola.atlassian.net/browse/COM-110

Tu sa to asi moze zavret.

**Comment by ondrajodas** [comment]
Udělal jsem retry na ErrorException a pokud se to ani tak nepovede tak to vyhodíme jako UserException
