### ISSUE TITLE
Add retry mechanism 

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/ex-ftp#22]
Ref.: https://keboola.zendesk.com/agent/tickets/10919

Currently connection is retried 3 times internally, but it happens withing few milliseconds.

**Comment by eddycek** [comment]
@tomasfejfar prosím přístup do zendesku, případně zaslat info z ticketu do DM na Slack. Díky

**Comment by yustme** [comment]
@eddycek máš nasdílený 1P Vault? Tam to heslo je. Jmenuje se to `Keboola TECH Zendesk`

**Comment by eddycek** [comment]
@yustme nemám, zažádám si

**Comment by tomasfejfar** [comment]
Aby tě to nebrzdilo - problém byl, že se jim nedařilo připojit k serveru. To se může stát. A ideálně bysme v takovou chvíli měli zkusit chvilku počkat a pak se zkusit připojit znova. 

Nejlepší by bylo, aby to dělaly úplně všechny akce nad FTP, ale tam je relativně obtížné zjistit, co vlastně můžeš a co nemůžeš opakovat (mazání, vytváření, přesouvání, atp.) takže aktuálně by bylo fajn vyřešit to připojení. 

Máme na to https://github.com/keboola/retry
