### ISSUE TITLE
lftp

### ISSUE THREAD

**Issue by zajca** [keboola/ex-ftp#25]
Náhodú sem procházel co tu je za issue a docela dost věcí souvisí s limitama flysystem.

Co použít normálně cli `lftp`. Docela by to mohlo zjednodušit celý extractor.

Umí toho mrdy ftp, sftp, torrent, http. Jde mu nastavit timeouty retry a dalších asi milion kravin.

Taky jde všechno nascriptovat takže se dá uživateli otevřít i celé rozhraní a může komplet nascriptovat co má lftp dělat.

příklad:
```
$ lftp -c "
set net:timeout 5;
set net:max-retries 3;
open $HOST
user $USER $PASS
mirror $SERVER_SOURCE $CLIENT_TARGET
exit
"
```
```
$ lftp -u $USER,$PASS $HOST -c "
set net:timeout 5;
set net:max-retries 3;
mirror $SERVER_SOURCE $CLIENT_TARGET
exit
"
```

https://lftp.yar.ru/lftp-man.html

**Comment by eddycek** [comment]
@zajca to není špatný nápad, co myslíš @yustme?

**Comment by yustme** [comment]
pokud to není úplně simple implementace, tak nemá smysl začít stavět knihovnu kolem console commandu. Nemá třeba už někdo hotovou implementaci v PHP ?

**Comment by zajca** [comment]
Právě bych kolem toho nic nestavěl. Nechal bych uživatele vytvořit celý ten vstup pro lftp mohl by to být template string aby tam šlo injectnút heslo.
Udělal bych nějaké příklady aby to pokrylo běžné užívání.

Kdyby to mělo být userfriendly tak by šlo rozdělit na dva "módy" to co sem popsal by bylo advanced. A nějaký simple by byl přednastavených ke stažení souboru nebo složek.

**Comment by yustme** [comment]
A máš konkrétní use-case, co by nám to přineslo? Já si myslím, že je už teďka většina věcí pofixovaná

**Comment by zajca** [comment]
Pokud je to extraktor teď v pořádku, tak je to práce zbytečně navíc.
Primárně by to zjednodušilo extraktor, protože by mohlo všechno jít na uživatele, ale zas by bylo složitější zachovat kompatibilitu se současnýma parametrama.

Zavřu issue, kdyby něco tak třeba good to know.
