### ISSUE TITLE
Move "New Files" filtering to earlier

### ISSUE THREAD

**Issue by pivnicek** [keboola/ex-ftp#28]
It would be clearer for the user imho, if the `NewFilesOnly` filtering were done earlier in the run, like maybe here where you get the timestamp anyways https://github.com/keboola/ex-ftp/blob/18425661fe0c42ffa1d1c92431f93f06c5ce791d/src/FtpExtractor.php#L139 .

We could compare with the saved state timestamp there.  

This way the list of files to process would A) be shorter, and B) be more accurately reflected in the logs.

**Comment by pivnicek** [comment]
https://keboola.zendesk.com/agent/tickets/11706

**Comment by ondrejhlavacek** [comment]
@marc any update here?
