### ISSUE TITLE
Excess traversing of whole ftp server?

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/ex-ftp#5]

**Comment by JakubMatejka** [comment]
Určitě je potřeba traverzovat celý server, když chci stáhnout soubor z konkrétního adresáře? Resp. mi není jasný proč se tady prochází 5200 souborů, když v tom zadaným adresáři jich je asi 20:
<img width="649" alt="test 2019-01-11 13-12-12" src="https://user-images.githubusercontent.com/215660/51033220-f1600d80-15a2-11e9-8f70-27fc1336928e.png">

**Comment by yustme** [comment]
To je trochu problém glob a knihovny, kterou jsem použil. Vylistujou se všechny soubory a pak se ověřujou oproti glob.

Mrknu se na to.

**Comment by eddycek** [comment]
@JakubMatejka Udělal jsem si u sebe na locale test a imho to funguje správně. Když zadáš cestu k adresáři, ze kterého chceš stáhnout všechny soubory se specifickou koncovkou, traverzuje se pouze ta složka a její podsložky, nic víc. Ve tvém případě musely ty podsložky obsahovat tak velké množství souborů.

![keboola_ex-ftp_issues_5](https://user-images.githubusercontent.com/1696274/64189698-321ad880-ce4b-11e9-8c9f-8d5a58d3aa20.png)

- path `/_data/` obsahuje velké množství složek/souborů
- path `/_data/test1/` obsahuje pouze 4 soubory
- path `/_data/test2/` pouze jeden soubor ale podsložka `others` obsahuje dalších 29 souborů

Dle mého je tohle chování naprosto očekávané a řekl bych, že většina uživatelů s tím i tak počítá. Omezovat zápis na stahování bez rekurze by mohlo zásadně ovlivnit chování současných instancí.

Nicméně `league/flysystem-sftp` na tohle myslí a má pro recursive list contents nastavení, dokonce ho máme i jako privátní property https://github.com/keboola/ex-ftp/blob/master/src/FtpExtractor.php#L18

Pakliže to potřebujeme ovlivnit, vytáhl bych to jako volitelný parametr do configu, s tím že default bude true jako teď. Je to potřeba nebo to necháme tak jak je?

**Comment by JakubMatejka** [comment]
Aha! Jasně, rozumím. Hmm, myslíš že je to potřeba resp. bude se to hodit? (přidat parametr co vypne `RECURSIVE_COPY`) @yustme

**Comment by yustme** [comment]
No můžeme zkusit zapínat rekurzi podle [reguláru](https://regex101.com/r/PZBeCg/1/), ale to mi přijde trochu risky.

Věc se má tak, že pokud server podporuje rekurzivní listování (to podporuje většina až na Microsoft), tak se všechny soubory získají jedním commandem `LIST -alnR`  a vlastně nemáš šanci (a ani nejspíš důvod) to nějak filtrovat. Pokud rek. listování server nepodporuje, tak musím reálně otevřít všechny složky ručně a porovnat je a to může být už náročnější.

Pokud bych se tedy do něčeho pouštěl, tak bych zkusil udělat, že při zapnutém parametru [recurseManually](https://github.com/keboola/ex-ftp/blob/fb433ec9b52a4ab893b6dc608c5d100bc2829b07/src/Config.php#L19) se udělá ten regular a zjistí se jestli je opravdu potřeba listovat všechny podsložky. Dává vám to smysl ?

**Comment by tomasfejfar** [comment]
Máš pravdu - regulár je risky :) https://regex101.com/r/PZBeCg/2 (jestli to chápu správně)

**Comment by yustme** [comment]
> Máš pravdu - regulár je risky :) https://regex101.com/r/PZBeCg/2 (jestli to chápu správně)

jo přesně takovýhle use-case tam budou a najednou to zázračně přestane fungovat.

**Comment by eddycek** [comment]
Pakliže tuhle funkcionalitu opravdu potřebujeme, zkusil bych to udělat jak píše @yustme. Nicméně regulár budu muset řádně otestovat a vyladit, aby to fakt fungovalo.

**Comment by yustme** [comment]
To je právě, že otázka jestli to nepřinese víc problémů než užitku. Podívám se kolik existuje konfigurací, které používají `recurseManully`

**Comment by yustme** [comment]
No tak vzhledem k tomu, že ten parametr nemá podporu v UI a dá se konfigurovat jenom v Advanced JSON configu, tak jsem zjistil, že ho nikdo nepoužívá.
```sql
SELECT "idProject", "name", "description",parse_json("configuration"):"parameters"
FROM "component-configurations-eu"
WHERE "idComponent" = 'keboola.ex-ftp' and parse_json("configuration"):"parameters":"recurseManually" IS NOT NULL;
```
 > 0 rows

Tím pádem to nemá smysl řešit a uzavírám issue.

**Comment by eddycek** [comment]
Ok, díky všem za konzultaci
